/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiIndexRouteImport } from './routes/api/index'
import { Route as ApiSyncRouteImport } from './routes/api/sync'
import { Route as ApiSuggestionRouteImport } from './routes/api/suggestion'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiRecordsRouteImport } from './routes/api/records'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as ApiSavedsIndexRouteImport } from './routes/api/saveds/index'
import { Route as ApiMangaIndexRouteImport } from './routes/api/manga/index'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as ApiSavedsRemoveRouteImport } from './routes/api/saveds/remove'
import { Route as ApiSavedsHashRouteImport } from './routes/api/saveds/hash'
import { Route as ApiSavedsDeletedRouteImport } from './routes/api/saveds/deleted'
import { Route as ApiSavedsAddRouteImport } from './routes/api/saveds/add'
import { Route as ApiImageSplatRouteImport } from './routes/api/image/$'
import { Route as ApiAuthRefreshRouteImport } from './routes/api/auth/refresh'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiMangaIdIndexRouteImport } from './routes/api/manga/$id/index'
import { Route as AuthedDashboardUserIndexRouteImport } from './routes/_authed/dashboard/user/index'
import { Route as AuthedDashboardMangaIdIndexRouteImport } from './routes/_authed/dashboard/$mangaId/index'
import { Route as AuthedDashboardMangaIdChapterIdRouteImport } from './routes/_authed/dashboard/$mangaId/$chapterId'
import { Route as ApiMangaIdChapterChapterIdRouteImport } from './routes/api/manga/$id/chapter/$chapterId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIndexRoute = ApiIndexRouteImport.update({
  id: '/api/',
  path: '/api/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRoute = ApiSyncRouteImport.update({
  id: '/api/sync',
  path: '/api/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuggestionRoute = ApiSuggestionRouteImport.update({
  id: '/api/suggestion',
  path: '/api/suggestion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecordsRoute = ApiRecordsRouteImport.update({
  id: '/api/records',
  path: '/api/records',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiSavedsIndexRoute = ApiSavedsIndexRouteImport.update({
  id: '/api/saveds/',
  path: '/api/saveds/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMangaIndexRoute = ApiMangaIndexRouteImport.update({
  id: '/api/manga/',
  path: '/api/manga/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const ApiSavedsRemoveRoute = ApiSavedsRemoveRouteImport.update({
  id: '/api/saveds/remove',
  path: '/api/saveds/remove',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSavedsHashRoute = ApiSavedsHashRouteImport.update({
  id: '/api/saveds/hash',
  path: '/api/saveds/hash',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSavedsDeletedRoute = ApiSavedsDeletedRouteImport.update({
  id: '/api/saveds/deleted',
  path: '/api/saveds/deleted',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSavedsAddRoute = ApiSavedsAddRouteImport.update({
  id: '/api/saveds/add',
  path: '/api/saveds/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageSplatRoute = ApiImageSplatRouteImport.update({
  id: '/api/image/$',
  path: '/api/image/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRefreshRoute = ApiAuthRefreshRouteImport.update({
  id: '/api/auth/refresh',
  path: '/api/auth/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMangaIdIndexRoute = ApiMangaIdIndexRouteImport.update({
  id: '/api/manga/$id/',
  path: '/api/manga/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardUserIndexRoute =
  AuthedDashboardUserIndexRouteImport.update({
    id: '/user/',
    path: '/user/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardMangaIdIndexRoute =
  AuthedDashboardMangaIdIndexRouteImport.update({
    id: '/$mangaId/',
    path: '/$mangaId/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardMangaIdChapterIdRoute =
  AuthedDashboardMangaIdChapterIdRouteImport.update({
    id: '/$mangaId/$chapterId',
    path: '/$mangaId/$chapterId',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const ApiMangaIdChapterChapterIdRoute =
  ApiMangaIdChapterChapterIdRouteImport.update({
    id: '/api/manga/$id/chapter/$chapterId',
    path: '/api/manga/$id/chapter/$chapterId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthedDashboardRouteWithChildren
  '/api/records': typeof ApiRecordsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/suggestion': typeof ApiSuggestionRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/': typeof ApiIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/image/$': typeof ApiImageSplatRoute
  '/api/saveds/add': typeof ApiSavedsAddRoute
  '/api/saveds/deleted': typeof ApiSavedsDeletedRoute
  '/api/saveds/hash': typeof ApiSavedsHashRoute
  '/api/saveds/remove': typeof ApiSavedsRemoveRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
  '/api/manga/': typeof ApiMangaIndexRoute
  '/api/saveds/': typeof ApiSavedsIndexRoute
  '/dashboard/$mangaId/$chapterId': typeof AuthedDashboardMangaIdChapterIdRoute
  '/dashboard/$mangaId/': typeof AuthedDashboardMangaIdIndexRoute
  '/dashboard/user/': typeof AuthedDashboardUserIndexRoute
  '/api/manga/$id/': typeof ApiMangaIdIndexRoute
  '/api/manga/$id/chapter/$chapterId': typeof ApiMangaIdChapterChapterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/api/records': typeof ApiRecordsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/suggestion': typeof ApiSuggestionRoute
  '/api/sync': typeof ApiSyncRoute
  '/api': typeof ApiIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/image/$': typeof ApiImageSplatRoute
  '/api/saveds/add': typeof ApiSavedsAddRoute
  '/api/saveds/deleted': typeof ApiSavedsDeletedRoute
  '/api/saveds/hash': typeof ApiSavedsHashRoute
  '/api/saveds/remove': typeof ApiSavedsRemoveRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/api/manga': typeof ApiMangaIndexRoute
  '/api/saveds': typeof ApiSavedsIndexRoute
  '/dashboard/$mangaId/$chapterId': typeof AuthedDashboardMangaIdChapterIdRoute
  '/dashboard/$mangaId': typeof AuthedDashboardMangaIdIndexRoute
  '/dashboard/user': typeof AuthedDashboardUserIndexRoute
  '/api/manga/$id': typeof ApiMangaIdIndexRoute
  '/api/manga/$id/chapter/$chapterId': typeof ApiMangaIdChapterChapterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/signup': typeof SignupRoute
  '/_authed/dashboard': typeof AuthedDashboardRouteWithChildren
  '/api/records': typeof ApiRecordsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/suggestion': typeof ApiSuggestionRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/': typeof ApiIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/image/$': typeof ApiImageSplatRoute
  '/api/saveds/add': typeof ApiSavedsAddRoute
  '/api/saveds/deleted': typeof ApiSavedsDeletedRoute
  '/api/saveds/hash': typeof ApiSavedsHashRoute
  '/api/saveds/remove': typeof ApiSavedsRemoveRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/api/manga/': typeof ApiMangaIndexRoute
  '/api/saveds/': typeof ApiSavedsIndexRoute
  '/_authed/dashboard/$mangaId/$chapterId': typeof AuthedDashboardMangaIdChapterIdRoute
  '/_authed/dashboard/$mangaId/': typeof AuthedDashboardMangaIdIndexRoute
  '/_authed/dashboard/user/': typeof AuthedDashboardUserIndexRoute
  '/api/manga/$id/': typeof ApiMangaIdIndexRoute
  '/api/manga/$id/chapter/$chapterId': typeof ApiMangaIdChapterChapterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signup'
    | '/dashboard'
    | '/api/records'
    | '/api/search'
    | '/api/suggestion'
    | '/api/sync'
    | '/api/'
    | '/api/auth/login'
    | '/api/auth/refresh'
    | '/api/image/$'
    | '/api/saveds/add'
    | '/api/saveds/deleted'
    | '/api/saveds/hash'
    | '/api/saveds/remove'
    | '/dashboard/'
    | '/api/manga/'
    | '/api/saveds/'
    | '/dashboard/$mangaId/$chapterId'
    | '/dashboard/$mangaId/'
    | '/dashboard/user/'
    | '/api/manga/$id/'
    | '/api/manga/$id/chapter/$chapterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signup'
    | '/api/records'
    | '/api/search'
    | '/api/suggestion'
    | '/api/sync'
    | '/api'
    | '/api/auth/login'
    | '/api/auth/refresh'
    | '/api/image/$'
    | '/api/saveds/add'
    | '/api/saveds/deleted'
    | '/api/saveds/hash'
    | '/api/saveds/remove'
    | '/dashboard'
    | '/api/manga'
    | '/api/saveds'
    | '/dashboard/$mangaId/$chapterId'
    | '/dashboard/$mangaId'
    | '/dashboard/user'
    | '/api/manga/$id'
    | '/api/manga/$id/chapter/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/signup'
    | '/_authed/dashboard'
    | '/api/records'
    | '/api/search'
    | '/api/suggestion'
    | '/api/sync'
    | '/api/'
    | '/api/auth/login'
    | '/api/auth/refresh'
    | '/api/image/$'
    | '/api/saveds/add'
    | '/api/saveds/deleted'
    | '/api/saveds/hash'
    | '/api/saveds/remove'
    | '/_authed/dashboard/'
    | '/api/manga/'
    | '/api/saveds/'
    | '/_authed/dashboard/$mangaId/$chapterId'
    | '/_authed/dashboard/$mangaId/'
    | '/_authed/dashboard/user/'
    | '/api/manga/$id/'
    | '/api/manga/$id/chapter/$chapterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  SignupRoute: typeof SignupRoute
  ApiRecordsRoute: typeof ApiRecordsRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiSuggestionRoute: typeof ApiSuggestionRoute
  ApiSyncRoute: typeof ApiSyncRoute
  ApiIndexRoute: typeof ApiIndexRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthRefreshRoute: typeof ApiAuthRefreshRoute
  ApiImageSplatRoute: typeof ApiImageSplatRoute
  ApiSavedsAddRoute: typeof ApiSavedsAddRoute
  ApiSavedsDeletedRoute: typeof ApiSavedsDeletedRoute
  ApiSavedsHashRoute: typeof ApiSavedsHashRoute
  ApiSavedsRemoveRoute: typeof ApiSavedsRemoveRoute
  ApiMangaIndexRoute: typeof ApiMangaIndexRoute
  ApiSavedsIndexRoute: typeof ApiSavedsIndexRoute
  ApiMangaIdIndexRoute: typeof ApiMangaIdIndexRoute
  ApiMangaIdChapterChapterIdRoute: typeof ApiMangaIdChapterChapterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/': {
      id: '/api/'
      path: '/api'
      fullPath: '/api/'
      preLoaderRoute: typeof ApiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync': {
      id: '/api/sync'
      path: '/api/sync'
      fullPath: '/api/sync'
      preLoaderRoute: typeof ApiSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suggestion': {
      id: '/api/suggestion'
      path: '/api/suggestion'
      fullPath: '/api/suggestion'
      preLoaderRoute: typeof ApiSuggestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/records': {
      id: '/api/records'
      path: '/api/records'
      fullPath: '/api/records'
      preLoaderRoute: typeof ApiRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/saveds/': {
      id: '/api/saveds/'
      path: '/api/saveds'
      fullPath: '/api/saveds/'
      preLoaderRoute: typeof ApiSavedsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/manga/': {
      id: '/api/manga/'
      path: '/api/manga'
      fullPath: '/api/manga/'
      preLoaderRoute: typeof ApiMangaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/api/saveds/remove': {
      id: '/api/saveds/remove'
      path: '/api/saveds/remove'
      fullPath: '/api/saveds/remove'
      preLoaderRoute: typeof ApiSavedsRemoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/saveds/hash': {
      id: '/api/saveds/hash'
      path: '/api/saveds/hash'
      fullPath: '/api/saveds/hash'
      preLoaderRoute: typeof ApiSavedsHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/saveds/deleted': {
      id: '/api/saveds/deleted'
      path: '/api/saveds/deleted'
      fullPath: '/api/saveds/deleted'
      preLoaderRoute: typeof ApiSavedsDeletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/saveds/add': {
      id: '/api/saveds/add'
      path: '/api/saveds/add'
      fullPath: '/api/saveds/add'
      preLoaderRoute: typeof ApiSavedsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image/$': {
      id: '/api/image/$'
      path: '/api/image/$'
      fullPath: '/api/image/$'
      preLoaderRoute: typeof ApiImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/refresh': {
      id: '/api/auth/refresh'
      path: '/api/auth/refresh'
      fullPath: '/api/auth/refresh'
      preLoaderRoute: typeof ApiAuthRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/manga/$id/': {
      id: '/api/manga/$id/'
      path: '/api/manga/$id'
      fullPath: '/api/manga/$id/'
      preLoaderRoute: typeof ApiMangaIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/user/': {
      id: '/_authed/dashboard/user/'
      path: '/user'
      fullPath: '/dashboard/user/'
      preLoaderRoute: typeof AuthedDashboardUserIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/$mangaId/': {
      id: '/_authed/dashboard/$mangaId/'
      path: '/$mangaId'
      fullPath: '/dashboard/$mangaId/'
      preLoaderRoute: typeof AuthedDashboardMangaIdIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/$mangaId/$chapterId': {
      id: '/_authed/dashboard/$mangaId/$chapterId'
      path: '/$mangaId/$chapterId'
      fullPath: '/dashboard/$mangaId/$chapterId'
      preLoaderRoute: typeof AuthedDashboardMangaIdChapterIdRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/api/manga/$id/chapter/$chapterId': {
      id: '/api/manga/$id/chapter/$chapterId'
      path: '/api/manga/$id/chapter/$chapterId'
      fullPath: '/api/manga/$id/chapter/$chapterId'
      preLoaderRoute: typeof ApiMangaIdChapterChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedDashboardRouteChildren {
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
  AuthedDashboardMangaIdChapterIdRoute: typeof AuthedDashboardMangaIdChapterIdRoute
  AuthedDashboardMangaIdIndexRoute: typeof AuthedDashboardMangaIdIndexRoute
  AuthedDashboardUserIndexRoute: typeof AuthedDashboardUserIndexRoute
}

const AuthedDashboardRouteChildren: AuthedDashboardRouteChildren = {
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
  AuthedDashboardMangaIdChapterIdRoute: AuthedDashboardMangaIdChapterIdRoute,
  AuthedDashboardMangaIdIndexRoute: AuthedDashboardMangaIdIndexRoute,
  AuthedDashboardUserIndexRoute: AuthedDashboardUserIndexRoute,
}

const AuthedDashboardRouteWithChildren = AuthedDashboardRoute._addFileChildren(
  AuthedDashboardRouteChildren,
)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SignupRoute: SignupRoute,
  ApiRecordsRoute: ApiRecordsRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiSuggestionRoute: ApiSuggestionRoute,
  ApiSyncRoute: ApiSyncRoute,
  ApiIndexRoute: ApiIndexRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthRefreshRoute: ApiAuthRefreshRoute,
  ApiImageSplatRoute: ApiImageSplatRoute,
  ApiSavedsAddRoute: ApiSavedsAddRoute,
  ApiSavedsDeletedRoute: ApiSavedsDeletedRoute,
  ApiSavedsHashRoute: ApiSavedsHashRoute,
  ApiSavedsRemoveRoute: ApiSavedsRemoveRoute,
  ApiMangaIndexRoute: ApiMangaIndexRoute,
  ApiSavedsIndexRoute: ApiSavedsIndexRoute,
  ApiMangaIdIndexRoute: ApiMangaIdIndexRoute,
  ApiMangaIdChapterChapterIdRoute: ApiMangaIdChapterChapterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
